host:
  # web api host
  # you can use API and Web interface through this host
  # webapi: docker.dev.example.net
  webapi: localhost

  # host suffix
  # if you access to foo.dev.example.net, mirage search "foo" subdomain container
  reverse_proxy_suffix: .dev.example.net

listen:
  # listen address
  # default is only listen from localhost
  foreign_address: 127.0.0.1

  # listen port and reverse proxy port
  http:
    # listen 8080 and transport to container's 5000 port
    - listen: 8080
      target: 5000

  # not implemented
  # we recommend to use frontend http(like nginx) to SSL termination
  # HTTPS:
  #   - 443

docker:
  # if you use docker through http, specify like "http://localhost:4243"
  endpoint: unix:///var/run/docker.sock

  # if you specify this, fill the form as default value on web interface.
  # default_image: myapp:latest

  # specify host_config, see https://godoc.org/github.com/fsouza/go-dockerclient#HostConfig
  # host_config:
  #   # means `docker run -p 45000-46000:12345/tcp`
  #   PortBindings:
  #     "12345/tcp":
  #      -  HostPort: "45000-46000"
  #  # means `docker run --rm`
  #   AutoRemove: true

storage:
  datadir: ./data
  htmldir: ./html

parameters:
  - name: branch
    env: GIT_BRANCH
    rule: ""
    required: true
  # add your custom parameters here!
  # name is parameter name (passed by HTTP parameter)
  # env is environment variable for docker container
  # rule is constraint of value using regexp.
  # required means required or optional parameter (boolean value)


